Repository dita-ot/docs, pull requests merged in 2018-02, with the labels that each got.

#193 Suggested detail for DOTJ054E
  topics/DITA-messages-details.xml
Labels: coverage, enhancement

#195 Add usage examples of <ditafileset>
  topics/plugin-coding-conventions.dita
Labels: webedit

#194 Convert deprecated attributes to elements
  samples/hierarchy.ditamap
  samples/sequence.ditamap
  samples/tasks/washingthecar.xml
Labels: outdated content
