Repository dita-ot/docs, pull requests merged in 2018-10, with the labels that each got.

#227 Add JavaScript plug-in example
  resources/reltable.ditamap
  resources/source-files.ditamap
  samples/plugins/com.example.html5-javascript/build_html5-javascript.xml
  samples/plugins/com.example.html5-javascript/include/javascript.ftr.xml
  samples/plugins/com.example.html5-javascript/plugin.xml
  topics/html-customization-plugin-javascript.dita
  topics/html-customization-plugins.dita
  topics/html-customization.ditamap
Labels: feature

#226 Restore autogenerated properties template
  .gitattributes
  build.gradle
  resources/properties-file.xsl
Labels: bug, build

#230 Add XDITA section and more about MDITA and HDITA
  topics/lwdita-input.dita
Labels: feature

#231 Draft feature/enhancement items for 3.2 notes
  release-notes/index.dita
Labels: review
