Repository dita-ot/docs, pull requests merged in 2019-10, with the labels that each got.

#269 Promote “output formats” to top level of ToC
  index.dita
  resources/common-toc.ditamap
  topics/alternative-input-formats.dita
  topics/publishing.ditamap
  topics/transformations.ditamap
  userguide-book.ditamap
Labels: enhancement

#271 Remove references to unbundled TocJS plugin
  extension-points/extension-points-details.dita
  parameters/ant-parameters-details.dita
  reference/XhtmlTocjs.dita
  reference/reference.ditamap
  resources/conref-task.dita
  resources/reltable.ditamap
  resources/source-files.ditamap
  topics/DITA-messages-details.xml
  topics/dita2tocjs.dita
  topics/html-customization-navigation.dita
  topics/transformations.ditamap
Labels: outdated content

#272 Initial documentation for project files
  resources/external-links.ditamap
  resources/source-files.ditamap
  topics/project-files-json.dita
  topics/project-files-xml.dita
  topics/project-files-yaml.dita
  topics/publishing.ditamap
  topics/using-project-files.dita
Labels: feature

#273 Update Gradle wrapper to 5.6.2
  gradle/wrapper/gradle-wrapper.properties
Labels: process

#274 Remove references to unbundled troff plugin
  extension-points/extension-points-details.dita
  extension-points/extension-points.ditamap
  extension-points/plugin-extension-points-xslt-import.dita
  resources/conref-task.dita
  resources/reltable.ditamap
  resources/source-files.ditamap
  samples/ant_sample/sample_all.xml
  samples/ant_sample/sample_troff.xml
  topics/DITA-messages-details.xml
  topics/dita2troff.dita
  topics/plugin-overridestyle.dita
  topics/transformations.ditamap
Labels: outdated content

#276 Remove <div> surrounding indexterms
  parameters/ant-parameters-details.dita
  parameters/dita-command-arguments.dita
  parameters/generate-copy-outer.dita
  reference/implementation-dependent-features.dita
  release-notes/index.dita
  resources/reusable-components.dita
  topics/log-files.dita
  topics/markdown-dita-syntax-reference.dita
  topics/migrating-to-1.8.dita
  topics/migrating-to-2.1.dita
  topics/migrating-to-2.3.dita
  topics/migrating-to-2.4.dita
  topics/migrating-to-2.5.dita
  topics/migrating-to-3.0.dita
  topics/migrating-to-3.3.dita
  topics/pdf-customization-approaches.dita
  topics/plugin-coding-conventions.dita
  topics/plugin-configfile.dita
  topics/plugins-registry.dita
  topics/prerequisite-software.dita
Labels: refactoring

#264 Enable PDF index
  DITA-OT_docs.xpr
  parameters/ant-parameters-details.dita
  parameters/dita-command-arguments.dita
  parameters/generate-copy-outer.dita
  reference/implementation-dependent-features.dita
  reference/preprocess-copyfiles.dita
  reference/preprocessing.dita
  release-notes/index.dita
  resources/reusable-components.dita
  topics/DITA-messages-details.xml
  topics/alternative-input-formats.dita
  topics/custom-plugins.dita
  topics/html-customization-plugin-javascript.dita
  topics/html-customization.dita
  topics/implement-saxon-collation-uri-resolvers.dita
  topics/implement-saxon-customizations.dita
  topics/log-files.dita
  topics/lwdita-input.dita
  topics/markdown-dita-syntax-reference.dita
  topics/migrating-to-1.5.4.dita
  topics/migrating-to-1.8.dita
  topics/migrating-to-2.1.dita
  topics/migrating-to-2.3.dita
  topics/migrating-to-2.4.dita
  topics/migrating-to-2.5.dita
  topics/migrating-to-3.0.dita
  topics/migrating-to-3.3.dita
  topics/migration.dita
  topics/pdf-customization-approaches.dita
  topics/pdf-customization.dita
  topics/pdf-plugin-structure.dita
  topics/pdf-plugin-structure_fo-xsl.dita
  topics/pdf2-creating-change-bars.dita
  topics/plugin-applications.dita
  topics/plugin-coding-conventions.dita
  topics/plugin-configfile.dita
  topics/plugins-registry.dita
  topics/prerequisite-software.dita
  userguide-book.ditamap
Labels: feature

#277 Initial documentation for Docker images
  resources/external-links.ditamap
  resources/source-files.ditamap
  resources/subjectscheme-outputclass.ditamap
  topics/publishing.ditamap
  topics/using-docker-images.dita
Labels: feature
