Repository dita-ot/docs, pull requests merged in 2019-06, with the labels that each got.

#251 Amend exec command to fail on error
  samples/ant_sample/dita-cmd.xml
  topics/migrating-ant-to-dita.dita
Labels: bug

#252 Examples of project files
  samples/project-files/all.xml
  samples/project-files/common.json
  samples/project-files/common.xml
  samples/project-files/common.yaml
  samples/project-files/distribution-docs.xml
  samples/project-files/html.json
  samples/project-files/html.xml
  samples/project-files/html.yaml
  samples/project-files/htmlhelp.xml
  samples/project-files/pdf.xml
Labels: feature

#257 Add @outputclass controlled values
  resources/subjectscheme-outputclass.ditamap
  resources/subjectscheme.ditamap
Labels: enhancement
