Repository dita-ot/docs, pull requests merged in 2020-11, with the labels that each got.

#313 Update Gradle wrapper to 6.7
  .github/workflows/gradle-wrapper-validation.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement

#314 Fix Preview action
  .github/workflows/preview.yml
Labels: build, refactoring

#309 Store API documentation
  reference/reference.ditamap
  reference/store-api.dita
  resources/source-files.ditamap
  topics/plugin-coding-conventions.dita
Labels: feature

#319 Include params from transtypes that extend the transtype
  parameters/ant-parameters-details.dita
  resources/params.xsl
Labels: bug, build
