Repository dita-ot/docs, pull requests merged in 2024-02, with the labels that each got.

#535 Update docs GitHub Actions for 4.2
  .github/actions/render/action.yml
  .github/workflows/release.yml
Labels: release-updates

#538 Fix typos in documentation and code
  reference/extended-functionality.dita
  reference/markdown/Common-syntax.md
  reference/processing-structure.dita
  resources/dita-ot-doc.css
  samples/concepts/tools.xml
  samples/taskbook/webtrouble.dita
  topics/building-output.dita
  topics/implement-saxon-extension-functions.dita
  topics/plugin-configfile.dita
Labels: typo

#540 Update GitHub Actions and local configuration for tool versions
  .github/actions/render/action.yml
  .github/workflows/prettier.yml
  .github/workflows/release.yml
  .nvmrc
Labels: build
