Repository dita-ot/docs, pull requests merged in 2025-02, with the labels that each got.

#579 Add init subcommand
  parameters/dita-command-arguments.dita
Labels: feature

#586 #585: Refactor ToC/parts
  index.dita
  parameters/index.dita
  parameters/parameters.ditamap
  reference/markdown-formats.ditamap
  reference/reference.ditamap
  resources/common-toc.ditamap
  resources/reltable.ditamap
  resources/source-files.ditamap
  topics/building-output.dita
  topics/dita-ot-day-2014.ditamap
  topics/dita-ot-day-2015.ditamap
  topics/extending.dita
  topics/installing.dita
  topics/intro.ditamap
  topics/output-formats.dita
  topics/pdf-customization.dita
  topics/plugins-registry.dita
  topics/publishing.dita
  topics/troubleshooting-overview.dita
  topics/using-plugins.ditamap
  userguide-book.ditamap
Labels: enhancement

#593 Update bookmap theme
  samples/themes/dita-ot-docs-theme.yaml
Labels: enhancement, pdf, next

#596 Update docs GitHub Actions for 4.3
  .github/actions/render/action.yml
  .github/workflows/release.yml
Labels: release-updates
